### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by raiyansarker** [daniL16/action-clean-old-files#1]
Hi,
I am not sure how it is not working. Just copy pasted your example but it is giving me `error: pathspec 'develop' did not match any file(s) known to git` error. 

Here is my action,
```
name: Delete old backups

on:
  schedule:
    - cron:  '0 0 * * 0'
  workflow_dispatch:
  
jobs:
  delete_files:
    runs-on: ubuntu-latest
    name: Delete old backups
    steps:
      - uses: actions/checkout@master
      - uses: daniL16/action-clean-old-files@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          dir: './DNS/backup'
          base_branch: 'master'
          days_old: '90'
```

_**Let me is if there are ways to fix it!**_
